Migration to mongodb
anastasiiakuzyk/FinesApplication pull request #3
Opened 2023-09-28 16:49 UTC by anastasiiakuzyk

2023-09-28 19:09 UTC, ajax-shulepa-a requested changes

2023-09-28 19:09 UTC, ajax-shulepa-a commented on src/main/kotlin/ua/anastasiia/finesapp/controller/FineController.kt
> +    @PatchMapping("add_violation/{carPlate}/{ticketId}/{violationIds}")
```suggestion
    @PatchMapping("add_violation/car/{carPlate}/ticket/{ticketId}/violations/{violationIds}")
```
Having 3 ids in a row makes your url messy. use resource identifiers to make it more readable. applicable to all similar places

2023-09-28 19:09 UTC, ajax-shulepa-a commented on src/main/kotlin/ua/anastasiia/finesapp/controller/FineController.kt
> +@Suppress("TooManyFunctions")
think about how you can reorganize your API to have several controllers

2023-09-28 19:09 UTC, ajax-shulepa-a commented on src/main/kotlin/ua/anastasiia/finesapp/controller/FineController.kt
> +class FineController(val mongoFineService: MongoFineService) {
```suggestion
class FineController(val fineService: FineService) {
```
service is responsible for business logic, it should not depend on database details

2023-09-28 19:09 UTC, ajax-shulepa-a commented on src/main/kotlin/ua/anastasiia/finesapp/repository/MongoFineRepository.kt
> +    fun getAllFinesInLocation(longitude: Double, latitude: Double): List<MongoFine> {
I think it's hard to have fines at an exact location. you can search fines in some areas (like within 1km radius of location)

2023-09-28 19:09 UTC, ajax-shulepa-a commented on src/main/kotlin/ua/anastasiia/finesapp/repository/MongoFineRepository.kt
> +//            .mapNotNull { linkedHashMap ->
do not commit commented code

2023-09-29 15:47 UTC, anastasiiakuzyk commented on src/main/kotlin/ua/anastasiia/finesapp/exception/FineException.kt
> +open class FineException(override val message: String) : RuntimeException()
Thank you for your suggestion, I feel like there is no need in making this class sealed

2023-09-29 15:47 UTC, anastasiiakuzyk commented on src/main/kotlin/ua/anastasiia/finesapp/config/MongoConfig.kt
> +}
It was a mistake, I'll remove it

2023-09-29 15:48 UTC, anastasiiakuzyk commented on src/main/kotlin/ua/anastasiia/finesapp/validator/EnumValidatorConstraint.kt
> +        }
I love this refactoring, thx

2023-10-02 05:46 UTC, ajax-shulepa-a approved these changes
Good job. just fix minor issue and you can merge

2023-10-02 05:46 UTC, ajax-shulepa-a commented on src/main/kotlin/ua/anastasiia/finesapp/service/FineServiceImpl.kt
> +        }
It's better to check if it is DuplicateKeyException and then throw your custom exception. because there could be multiple reasons to have exception

2023-10-02 07:56 UTC, merged