Switched to reactor, added github actions
anastasiiakuzyk/FinesApplication pull request #5
Opened 2023-11-01 12:32 UTC by anastasiiakuzyk

2023-11-01 14:05 UTC, HNDaG approved these changes
Look good for me

2023-11-01 14:05 UTC, HNDaG commented on finesapp/src/main/kotlin/ua/anastasiia/finesapp/service/FineServiceImpl.kt
NIT. 

Don't like this code style. As for me kotlin like style is not always suitable to use. Now it's hard to comprehend this code for me.

2023-11-02 08:27 UTC, SlavikN14 approved these changes

2023-11-02 09:54 UTC, anastasiiakuzyk commented on finesapp/src/main/kotlin/ua/anastasiia/finesapp/service/FineServiceImpl.kt
> +        mongoFineRepository.getAllFines().map { it.toResponse() }.switchIfEmpty(NoFinesFoundException().toMono())
when I convert class NoFinesFoundException to object I get the warning: Serializable object must implement 'readResolve', don't want to do that..., `readResolve` feels odd

2023-11-02 11:04 UTC, anastasiiakuzyk commented on finesapp/src/main/kotlin/ua/anastasiia/finesapp/service/FineServiceImpl.kt
> +        mongoFineRepository.getAllFines().map { it.toResponse() }.switchIfEmpty(NoFinesFoundException().toMono())
okay, I managed to convert it to object, but I'll suppress the warning: @Suppress("JavaIoSerializableObjectMustHaveReadResolve")

2023-11-02 15:55 UTC, ajax-gnatiuk-s requested changes

2023-11-03 08:57 UTC, HNDaG commented on finesapp/src/main/kotlin/ua/anastasiia/finesapp/service/FineServiceImpl.kt
So I don't think that using kotlin style return from **fun8** is always suitable to use. As for me, I think that using such style is better for small lambda-like fun and not in a big fun. Even if the only thing you do is return a big reactive pipeline. After all in you service there are lots of methods like this, it becomes easy to mess with code formatting and in general code easily blends together. So my point is that this is better -> 
***
    override fun removeViolationFromTicket(carPlate: String, ticketId: ObjectId, violationId: Int): Mono<FineResponse> {
        return mongoFineRepository.removeViolationFromTicket(
            carPlate,
            ticketId,
            violationId.toViolationType().toViolation().description
        )
            .map { it.toResponse() }
            .switchIfEmpty(TrafficTicketWithViolationNotFoundException(ticketId, violationId).toMono())
    }
***

2023-11-03 16:35 UTC, ajax-gnatiuk-s approved these changes

2023-11-03 16:35 UTC, ajax-gnatiuk-s commented on finesapp/src/main/kotlin/ua/anastasiia/finesapp/service/FineServiceImpl.kt
So, you prefer `block body` instead of `expression body` for more complex functions. In general I agree with you.

Nevertheless, you marked this thread as **NIT**, so it's up to the author to apply the suggestion :)

2023-11-08 08:45 UTC, merged